import PDFDocument from "pdfkit"

export const generateResumePdf = async (data) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
      info: {
        Author: "DarshAI",
        Title: `${data.name} - Resume`,
        Creator: "DarshAI"
      }
    })

    const chunks = []
    doc.on("data", (chunk) => chunks.push(chunk))
    doc.on("end", () => resolve(Buffer.concat(chunks)))
    doc.on("error", reject)

    const primary = "#1e293b"
    const accent = "#6366f1"
    const gray = "#64748b"
    const lightBg = "#f8fafc"

    const underline = (y, w, color) => {
      doc.moveTo(50, y).lineTo(50 + w, y).strokeColor(color).lineWidth(2).stroke()
    }

    // Name
    doc.fontSize(26).font("Helvetica-Bold").fillColor(primary).text(data.name || "Your Name", 50, 50, { align: "left" })

    // Contact
    const contact = [data.email, data.phone, data.location].filter(Boolean).join("  |  ")
    if (contact) {
      doc.fontSize(10).font("Helvetica").fillColor(gray).text(contact, 50, doc.y + 4, { align: "left" })
    }

    doc.moveDown(1.5)

    // Professional Summary
    if (data.summary) {
      doc.moveDown(0.5)
      doc.fontSize(14).font("Helvetica-Bold").fillColor(accent).text("PROFESSIONAL SUMMARY")
      underline(doc.y + 2, 180, accent)
      doc.moveDown(0.8)
      doc.fontSize(10).font("Helvetica").fillColor(primary).text(data.summary, { lineGap: 4 })
      doc.moveDown(1)
    }

    // Skills
    if (data.skills?.length > 0) {
      doc.fontSize(14).font("Helvetica-Bold").fillColor(accent).text("SKILLS")
      underline(doc.y + 2, 60, accent)
      doc.moveDown(0.8)
      const skillGroups = data.skills.map((s) => `${s.category || "General"}: ${s.items?.join(", ") || ""}`).join("\n")
      doc.fontSize(10).font("Helvetica").fillColor(primary).text(skillGroups, { lineGap: 4 })
      doc.moveDown(1)
    }

    // Experience
    if (data.experience?.length > 0) {
      doc.fontSize(14).font("Helvetica-Bold").fillColor(accent).text("EXPERIENCE")
      underline(doc.y + 2, 100, accent)
      doc.moveDown(0.8)
      data.experience.forEach((exp) => {
        doc.fontSize(11).font("Helvetica-Bold").fillColor(primary).text(exp.title || "")
        doc.fontSize(10).font("Helvetica").fillColor(gray).text(`${exp.company || ""}${exp.dates ? ` | ${exp.dates}` : ""}`)
        doc.moveDown(0.3)
        if (exp.points?.length > 0) {
          exp.points.forEach((p) => {
            doc.fontSize(10).font("Helvetica").fillColor(primary).text(`• ${p}`, { indent: 10, lineGap: 3 })
          })
        }
        doc.moveDown(0.5)
      })
      doc.moveDown(0.5)
    }

    // Education
    if (data.education?.length > 0) {
      doc.fontSize(14).font("Helvetica-Bold").fillColor(accent).text("EDUCATION")
      underline(doc.y + 2, 90, accent)
      doc.moveDown(0.8)
      data.education.forEach((edu) => {
        doc.fontSize(11).font("Helvetica-Bold").fillColor(primary).text(edu.degree || "")
        doc.fontSize(10).font("Helvetica").fillColor(gray).text(`${edu.institution || ""}${edu.year ? ` | ${edu.year}` : ""}`)
        doc.moveDown(0.5)
      })
      doc.moveDown(0.5)
    }

    // Certifications
    if (data.certifications?.length > 0) {
      doc.fontSize(14).font("Helvetica-Bold").fillColor(accent).text("CERTIFICATIONS")
      underline(doc.y + 2, 120, accent)
      doc.moveDown(0.8)
      data.certifications.forEach((cert) => {
        doc.fontSize(10).font("Helvetica").fillColor(primary).text(`• ${cert.name || cert}${cert.issuer ? ` — ${cert.issuer}` : ""}`, { indent: 10, lineGap: 3 })
      })
      doc.moveDown(0.5)
    }

    // Projects
    if (data.projects?.length > 0) {
      doc.fontSize(14).font("Helvetica-Bold").fillColor(accent).text("PROJECTS")
      underline(doc.y + 2, 80, accent)
      doc.moveDown(0.8)
      data.projects.forEach((proj) => {
        doc.fontSize(11).font("Helvetica-Bold").fillColor(primary).text(proj.name || "")
        if (proj.description) {
          doc.fontSize(10).font("Helvetica").fillColor(primary).text(proj.description, { lineGap: 3 })
        }
        doc.moveDown(0.5)
      })
    }

    // Footer
    doc.moveDown(2)
    doc.fontSize(9).font("Helvetica").fillColor(gray).text("Generated by DarshAI", 50, doc.y, { align: "center" })

    doc.end()
  })
}